### ISSUE TITLE
分组管理页面长名称显示异常

### ISSUE THREAD

**Issue by Catomorphism** [longguikeji/arkid-frontend#8]
如图
<img width="311" alt="屏幕快照 2019-09-26 下午5 26 24" src="https://user-images.githubusercontent.com/55833546/65677143-a7ad4980-e083-11e9-9e1b-48c9e64ec078.png">

**Comment by lukaishun** [comment]
#14

**Comment by RockLi** [comment]
bug fixed and closed the issue.
